// LogMeVersion.hpp
// Generated by CMake

namespace LogMe
{
const int32_t CM_VERSION_MAJOR = @LogMe_VERSION_MAJOR@;
const int32_t CM_VERSION_MINOR = @LogMe_VERSION_MINOR@;
const int32_t CM_VERSION_PATCH = @LogMe_VERSION_PATCH@;
const std::string CM_VERSION_STRING = "v@LogMe_VERSION@";

const std::string CM_APP_CMAKE_NAME = "@PROJECT_NAME@";
const std::string CM_APP_CMAKE_DESCRIPTION = "@LogMe_DESCRIPTION@";
};
